Controllers/BlogMaintenanceController.cs
using System;
using Microsoft.AspNet.Mvc;
using System.Linq;
using System.Collections.Generic;
using weblog.Models.Blog;
using weblog.ViewComponents;

namespace weblog.Controllers
{
    public class BlogMaintenanceController : Controller
    {
        private BlogDbContext _context;
        private List<Post> Posts;
        
        public BlogMaintenanceController(BlogDbContext context)
        {
            _context = context;
        }
        
        public IActionResult Index()
        {
            return View("Index");
        }
        
        public IActionResult NewPost()
        {
            return View();
        }
        
        public IActionResult EditPost(int? id)
        {
            Post post = _context.Posts.Single(p => p.PostId == id);
            
            if (post == null)
            {
                return HttpNotFound();
            }
            
            return View("NewPost", post);
        }

        /*public IActionResult Create()
        {
            return View("Index");//RedirectToAction(nameof(Index));
        }*/
        
        [HttpPost]
        public IActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.Status = Post.PostStatus.Draft;
                _context.Posts.Add(post);
                _context.SaveChanges();
                
                //RedirectToAction("Index", "BlogMaintenance");
            }
            
            return RedirectToAction("Index", "BlogMaintenance");

           // return View("Index");//RedirectToAction(nameof(Index));
            
        }
        
        public IActionResult SavePost(Post post)
        {
            if (ModelState.IsValid)
            {
                /*if (post.PostId == 0)
                {
                    _context.Posts.Add(post);
                    _context.SaveChanges();
                }
                else
                {*/
                    _context.Posts.Update(post);
                    _context.SaveChanges();
                //}
                
                //_context.
            }
            
            return RedirectToAction("EditPost", "BlogMaintenance", new {id = post.PostId});
        }


    }
}

ViewComponents/DraftPostsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using weblog.Models.Blog;

namespace weblog.ViewComponents
{
    public class DraftPostsViewComponent : ViewComponent
    {
        private BlogDbContext _context;
        
        public DraftPostsViewComponent(BlogDbContext context)
        {
            _context = context;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var drafts = await GetDraftsAsync();
            return View(drafts);
        }
        
        private Task<List<Post>> GetDraftsAsync()
        {
            return _context.Posts.Where(d => d.Status == Post.PostStatus.Draft).ToListAsync();
        }
        
    }
}

Views/BlogMaintenance/NewPost.cshtml
@model weblog.Models.Blog.Post



<!--<div class="container full-height editor">-->

    <form asp-controller="BlogMaintenance" asp-action="SavePost" method="POST" role="form" class="form-horizontal full-height">
        <input type="hidden" asp-for="PostId" />
        
        <div class="container action-pane">
            <div class="col-md-3 col-md-offset-9">
                <button type="submit" class="btn btn-default">Save</button>
            </div>
        </div> 
        
        <div class="container">
            <div class="col-md-12"><input asp-for="Title" class="post-editor-title" tabindex="0" autofocus placeholder="Your Post Title" /></div>
        </div>
        
        <div class="container full-height editor">                     
            <div class="col-md-6 full-height">
                <textarea asp-for="Content" class="post-editor-content full-height" id="wmd-input" placeholder="Your post content."></textarea>
            </div>
            <div class="col-md-6 full-height post-editor-liveview" id="wmd-preview"></div>               
        </div>
    </form>

<!--</div>-->

<environment names="Development">
    <script src="~/js/Markdown.Converter.js"></script>
    <script src="~/js/Markdown.Editor.js"></script>
    <script src="~/js/Markdown.Sanitizer.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/Markdown.Converter.js" asp-append-version="true"></script>
    <script src="~/js/Markdown.Editor.js" asp-append-version="true"></script>
    <script src="~/js/Markdown.Sanitizer.js" asp-append-version="true"></script>
</environment>

<script type="text/javascript">
    (function () {
        var converter = Markdown.getSanitizingConverter();
        
        converter.hooks.chain("preBlockGamut", function (text, rbg) {
            return text.replace(/^ {0,3}""" *\n((?:.*?\n)+?) {0,3}""" *$/gm, function (whole, inner) {
                return "<blockquote>" + rbg(inner) + "</blockquote>\n";
            });
        });
        
        var editor = new Markdown.Editor(converter);
        
        editor.run();
    })();
</script>

Views/BlogMaintenance/index.cshtml
@model weblog.Models.Blog.Post

<h2>Create new post</h2>
<form asp-controller="BlogMaintenance" asp-action="Create" method="POST" role="form" class="form-horizontal">
    <label asp-for="Title" class="control-label">Title:</label>
    <input asp-for="Title" class="form-control" />
    <button type="submit" class="btn btn-default">Create</button>
</form>

@await Component.InvokeAsync("DraftPosts")